spring:
  application:
    name:
      netty

netty:
  server:
    tcp:
      echo:
        properties:
          - identifier: tcp-echo1
            port: 3000
          - identifier: tcp-echo2
            port: 3001
      socks5:
        properties:
          - identifier: socks5-1
            port: 1080